baseURL = "https://skibohemen.github.io/nap-help/"
relativeURLs = "true"
languageCode = "no"
languageName = "Norsk"
title = "NAP - Norsk aksesspunkt for transport- og trafikkdata"
enableEmoji = "true"
enableGitInfo = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "silhouette-hugo"
publishDir = "docs"
imggroup = "sorfold"

[params]
  datacat = "https://fellesdatakatalog.brreg.no/?q=transport&theme=TRAN"
  author = "Statens vegvesen"
  introDescription = "Intro"
  [params.img]
     imgauthor = "Sørfold - Jarle Wæhler, Statens vegvesen"
     background_image = "images/Sorfold.jpg"
