baseURL = "https://skibohemen.github.io/nap-help"
relativeURLs = "true"
languageCode = "no"
defaultContentLanguage = "no"
defaultContentLanguageInSubdir = true
buildDrafts = true
enableEmoji = "true"
enableGitInfo = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "silhouette-hugo"
publishDir = "docs"
imggroup = "sorfold"

[languages]
  [languages.no]
   datacat = "https://fellesdatakatalog.brreg.no/?q=transport&theme=TRAN"
   datacatText = "Datakatalog"
   languageName = "Norsk"
   aboutText = "Om NAP"
   langText = "Språk"
   contentDir = "content/no"
   title = "Nasjonalt tilgangspunkt for transport- og trafikkdata"
   weight = 1

  [languages.en]
    datacat = "https://fellesdatakatalog.brreg.no/?q=transport&theme=TRAN&lang=en"
    datacatText = "Data Sets"
    languageName = "English"
    title = "Norwegian National Access Point"
    aboutText = "About NAP"
    langText = "Languages"
    contentDir = "content/en"
    weight = 2


[params]
  author = "Statens vegvesen"
  introDescription = "Intro"
  [params.img]
     imgauthor = "Sørfold - Jarle Wæhler, Statens vegvesen"
     background_image = "images/Sorfold.jpg"
