baseURL = "/"
languageCode = "en-us"
title = "NAP - Norwegian Access Point (for transportdata)"
enableEmoji = "true"
enableGitInfo = "true"
author = "Steinar Kjærnsrød"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "silhouette-hugo"

[params]
  dataut = "https://fellesdatakatalog.brreg.no/?q=transport&theme=TRAN"
