baseURL = "https://skibohemen.github.io/nap-help/"
languageCode = "en-us"
title = "NAP - Norsk aksesspunkt for transport- og trafikkdata"
enableEmoji = "true"
enableGitInfo = "true"
author = "Steinar Kjærnsrød"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "silhouette-hugo"
publishDir = "docs"

[params]
  datacat = "https://fellesdatakatalog.brreg.no/?q=transport&theme=TRAN"
  author = "Statens vegvesen"
