relativeURLs = "true"
buildDrafts = true
enableEmoji = "true"
enableGitInfo = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "silhouette-hugo"
publishDir = "docs"
imggroup = "sorfold"

[languages]
  [languages.en]
    baseURL = "https://skibohemen.github.io/nap-help/en/"
    languageName = "English"
    title = "Norwegian National Access Point"
    weight = 1
  [languages.no]
    baseURL = "https://skibohemen.github.io/nap-help/no/"
    languageName = "Norsk"
    title = "Nasjonalt tilgangspunkt for transport- og trafikkdata"
    weight = 2

[params]
  datacat = "https://fellesdatakatalog.brreg.no/?q=transport&theme=TRAN"
  author = "Statens vegvesen"
  introDescription = "Intro"
  [params.img]
     imgauthor = "Sørfold - Jarle Wæhler, Statens vegvesen"
     background_image = "images/Sorfold.jpg"
